(define (problem hanoi4) 
(:domain hanoi) 
(:objects t1 t2 t3 -table 
	  d1 d2 d3 d4 - disc) 
(:init (smaller t1 d1) 
       (smaller t1 d2) 
       (smaller t1 d3) 
       (smaller t1 d4)
       (smaller t2 d1) 
       (smaller t2 d2) 
       (smaller t2 d3) 
       (smaller t2 d4) 
       (smaller t3 d1) 
       (smaller t3 d2) 
       (smaller t3 d3) 
       (smaller t3 d4) 
       (smaller d2 d1) 
       (smaller d3 d1) 
       (smaller d3 d2) 
       (smaller d4 d1) 
       (smaller d4 d2) 
       (smaller d4 d3)
       (clear t2) 
       (clear t3) 
       (clear d1)
       (on d4 t1) 
       (on d3 d4) 
       (on d2 d3) 
       (on d1 d2))

(:goal (and (on d4 t3) 
            (on d3 d4) 
	    (on d2 d3) 
	    (on d1 d2)))
)  
